from genai.exceptions.genai_exception import GenAiException

__all__ = ["GenAiException"]
